# Generated by Django 4.2.16 on 2024-10-19 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "Cname",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("group", models.CharField(default="SB", max_length=20)),
                ("adr", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("gst", models.CharField(max_length=20)),
                ("pan", models.CharField(blank=True, max_length=20, null=True)),
                ("state", models.CharField(blank=True, max_length=30, null=True)),
                ("code", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lorry",
            fields=[
                (
                    "Lno",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("length", models.FloatField(blank=True, null=True)),
                ("width", models.FloatField(blank=True, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "name",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("quantity_per", models.FloatField()),
                ("pcs_fts", models.FloatField()),
                ("rate", models.FloatField()),
                ("tax_rate", models.FloatField()),
                ("hsn_code", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "fname",
                    models.CharField(max_length=55, primary_key=True, serialize=False),
                ),
                ("gst", models.CharField(blank=True, max_length=15, null=True)),
                ("adr", models.CharField(blank=True, max_length=200, null=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TempRate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=100)),
                ("product", models.CharField(max_length=100)),
                ("csoid", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TempTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                ("Invoice", models.CharField(blank=True, max_length=50, null=True)),
                ("Cadr", models.CharField(max_length=100)),
                ("Sadr", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=30, null=True)),
                ("code", models.FloatField(blank=True, null=True)),
                ("gst", models.CharField(blank=True, max_length=20, null=True)),
                ("date", models.DateField()),
                ("pcs", models.FloatField(blank=True, null=True)),
                ("InvoiceEnd", models.DateField(blank=True, null=True)),
                ("tax_rate", models.FloatField(blank=True, null=True)),
                ("lorry_no", models.CharField(max_length=20)),
                ("trip", models.FloatField()),
                ("challan", models.CharField(max_length=20)),
                ("hsn", models.CharField(max_length=20)),
                ("product", models.CharField(max_length=20)),
                ("rate", models.FloatField()),
                ("amount", models.FloatField(blank=True, null=True)),
                ("cgst", models.FloatField()),
                ("sgst", models.FloatField()),
                ("final_amount", models.FloatField()),
                ("total_amount", models.FloatField(blank=True, null=True)),
                (
                    "Cname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoiceApp.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("oid", models.AutoField(primary_key=True, serialize=False)),
                ("fname", models.CharField(max_length=50)),
                ("Pname", models.CharField(max_length=100)),
                ("Dname", models.CharField(max_length=20)),
                ("Lno", models.CharField(max_length=20)),
                ("pcno", models.CharField(max_length=20)),
                ("scno", models.CharField(max_length=20)),
                ("trip", models.FloatField(default=0)),
                ("df1", models.DateField(blank=True, null=True)),
                ("df2", models.DateField(blank=True, null=True)),
                ("df3", models.DateField(blank=True, null=True)),
                ("length", models.FloatField(blank=True, null=True)),
                ("width", models.FloatField(blank=True, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
                ("pcs", models.FloatField(blank=True, null=True)),
                ("amount", models.FloatField(blank=True, null=True)),
                ("billed", models.CharField(default="No", max_length=3)),
                (
                    "Cname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoiceApp.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoiceApp.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderGroupReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=100)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoiceApp.orders",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Billing",
            fields=[
                ("bill_id", models.AutoField(primary_key=True, serialize=False)),
                ("bill_date", models.DateField(blank=True, null=True)),
                ("final_rate", models.FloatField(blank=True, null=True)),
                ("material_rate", models.FloatField(blank=True, null=True)),
                ("transport_rate", models.FloatField(blank=True, null=True)),
                ("final_amount", models.FloatField(blank=True, null=True)),
                ("oid", models.TextField()),
                ("product", models.CharField(max_length=50)),
                ("place", models.CharField(max_length=50)),
                (
                    "Cname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoiceApp.customer",
                    ),
                ),
            ],
        ),
    ]
