# Generated by Django 4.2.16 on 2024-09-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('csoid', models.TextField()),
            ],
        ),
    ]
