# Generated by Django 4.2.16 on 2024-10-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoiceApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="Cname",
            field=models.CharField(max_length=50),
        ),
    ]
