# Generated by Django 4.2.16 on 2024-09-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0002_temprate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('Cname', models.CharField(max_length=20)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('final_rate', models.FloatField(blank=True, null=True)),
                ('material_rate', models.FloatField(blank=True, null=True)),
                ('transport_rate', models.FloatField(blank=True, null=True)),
                ('final_amount', models.FloatField(blank=True, null=True)),
                ('mcode', models.CharField(choices=[('M1', 'M1'), ('M2', 'M2')], max_length=20)),
                ('tcode', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2')], max_length=20)),
                ('oid', models.IntegerField()),
                ('product', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
            ],
        ),
    ]
