# Generated by Django 4.2.16 on 2024-10-19 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invoiceApp", "0002_alter_orders_cname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="Cname",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="invoiceApp.customer"
            ),
        ),
    ]
