# Generated by Django 4.2.16 on 2024-09-29 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0003_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='mcode',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='tcode',
        ),
    ]
