# Generated by Django 4.2.16 on 2024-09-29 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0004_remove_billing_mcode_remove_billing_tcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('Invoice', models.CharField(blank=True, max_length=50, null=True)),
                ('Cname', models.CharField(max_length=20)),
                ('Cadr', models.CharField(max_length=100)),
                ('Sadr', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('code', models.FloatField(blank=True, null=True)),
                ('gst', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField()),
                ('pcs', models.FloatField(blank=True, null=True)),
                ('InvoiceEnd', models.DateField(blank=True, null=True)),
                ('tax_rate', models.FloatField(blank=True, null=True)),
                ('lorry_no', models.CharField(max_length=20)),
                ('trip', models.FloatField()),
                ('challan', models.CharField(max_length=20)),
                ('hsn', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=20)),
                ('rate', models.FloatField()),
                ('amount', models.FloatField(blank=True, null=True)),
                ('cgst', models.FloatField()),
                ('sgst', models.FloatField()),
                ('final_amount', models.FloatField()),
                ('total_amount', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderGroupReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoiceApp.orders')),
            ],
        ),
    ]
