# Generated by Django 4.2.16 on 2024-09-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0005_record_temptable_ordergroupreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='oid',
            field=models.TextField(),
        ),
    ]
