# Generated by Django 4.2.16 on 2024-10-23 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invoiceApp", "0005_alter_orders_cname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="fname",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="invoiceApp.supplier"
            ),
        ),
    ]
