# Generated by Django 4.2.16 on 2024-10-23 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invoiceApp", "0006_alter_orders_fname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="Lno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="invoiceApp.lorry"
            ),
        ),
    ]
