# Generated by Django 4.2.16 on 2024-11-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoiceApp", "0008_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="purchaseRate",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
