# Generated by Django 4.2.16 on 2024-11-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoiceApp", "0011_alter_orders_purchaserate_alter_record_purchaserate"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="df2",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(default="unpaid", max_length=20),
        ),
    ]
